### ISSUE TITLE
Design Specific Colors

### ISSUE THREAD

**Issue by DuckMasterAl** [DuckMasterAl/DuckMasterAl.github.io#29]
**Is your feature request related to a problem?** 
Angelo doesn't like color scheme
**Describe the solution you'd like** 
Get better colors from this website [https://colors.eva.design/](https://colors.eva.design/)
**Additional context** 
Yea this is all @angeloanan's idea but he was too lazy to make a github issue about it >.>

**Comment by angeloanan** [comment]
what

**Comment by DuckMasterAl** [comment]
> what

I'm not doing this, so it's closed :^)
