### ISSUE TITLE
no license page on the website

### ISSUE THREAD

**Issue by yashvirsabharwal** [DuckMasterAl/DuckMasterAl.github.io#38]
**Website Page** 
/license
**To Reproduce**
Steps to reproduce the behavior (Optional):
go to the link
**What Happens?** 
404
**What Should Happen?** 
license page
**Additional context** 
fix

**Comment by DuckMasterAl** [comment]
You currently need to do go to [/LICENSE](https://bduck.xyz/LICENSE) (all caps).
This will be fixed whenever I redo the site.

**Comment by yashvirsabharwal** [comment]
makes sense. also, make it a txt file :)
