### ISSUE TITLE
Make a bio for socials

### ISSUE THREAD

**Issue by DuckMasterAl** [DuckMasterAl/DuckMasterAl.github.io#8]
Make a copy paste bio for socials and maybe also for the homepage.

**Comment by DuckMasterAl** [comment]
# Short Bio
Hi, I'm DuckMasterAl! I develop discord bots, like Quacky Bot, and love Ducks :duck:


# Long Bio
Hi, I'm DuckMasterAl! I develop discord bots, like @quacky-bot, and love Ducks :duck:
## Projects 💻 
Currently, my main project is @quacky-bot, but I also work on other things (small projects) and work on [my website!](https://duck.js.org)
### Commissions :octocat: 
Feel Free to Contact me on discord [@DuckMasterAl#0001](https://discord.com/users/443217277580738571) if you want a discord bot commission.
### Contact Me 📬 
You can contact me on any of my social medias, but you'll get a faster response time if you [email me](mailto:duckmaster.dev@gmail.com) or [DM Me on Discord.](https://discord.com/users/443217277580738571)

# Long Bio (Simple Markdown)
Hi, I'm DuckMasterAl! I develop discord bots, like Quacky Bot, and love Ducks :duck:
**Projects 💻**
Currently, my main project is Quacky Bot, but I also work on other things (small projects) and work on [my website!](https://duck.js.org)
**Commissions 🛰️**
Feel Free to Contact me on discord `@DuckMasterAl#0001` if you want a discord bot commission.
**Contact Me 📬**
You can contact me on any of my social medias, but you'll get a faster response time if you email me at duckmaster.dev@gmail.com or DM Me on Discord (`DuckMasterAl#0001`).

**Comment by DuckMasterAl** [comment]
# People's Opinions
> Looks good

~ @TheMoksej

> oh no that looks nice

~ @Cairo2k18

> It looks good!

~ imlonelyduck

> nice

~ @IceeMC

> Its good

~ @SirSpiceTheSpice

**Comment by TheMoksej** [comment]
lol
